name: Frontend CI/CD

on:
  push:
    branches: [deployment-frontend]
  pull_request:
    branches: [deployment-frontend]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Archive build output
      run: |
        tar -czf frontend-app.tar.gz -C dist .

    - name: Upload frontend archive to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "frontend-app.tar.gz"
        target: "/var/www/html"

    - name: Deploy frontend on EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: jesse
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd  /var/www/html
          rm -rf frontend-deploy
          mkdir frontend-deploy
          tar -xzf frontend-app.tar.gz -C frontend-deploy
         


